from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import mysql.connector
from mysql.connector import Error
import datetime
###СОЕДИНЕНИЕ С БД
def create_connection(host_name, user_name, user_password, db_name):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            database=db_name
        )
        print("Connection to MySQL DB successful")
    except Error as e:
        print(f"The error '{e}' occurred")
    return connection

connection = create_connection("localhost", "root", "Ddrkl#4321", 'organization_of_delivery')

###КУРСОР
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)  ###МЕТОД ДЛЯ ВЫПОЛНЕНИЯ ЗАПРОСОВ
        connection.commit()
        print("Query executed successfully")
    except Error as e:
        print(f"The error '{e}' occurred")

###ЧТЕНИЕ ИЗ БД
def execute_read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall()
        return result
    except Error as e:
        print(f"The error '{e}' occurred")

###ПОИСК ПО БД
def find(family, post, password, tab):
    select_users = f"SELECT * FROM {tab}"
    users = execute_read_query(connection, select_users)

    for user in users:
        if user[1]==family and user[5]==post and user[7]==password:
            showButtonsWindow()
            return
    message('Ошибка!', 'Пользователь не найден.')


###СОЗДАНИЕ ЗАПИСИ
def create(fam, po, passw, tab):
    family = fam
    post = po
    password = passw

    if family!='' and post!='' and password !='':
        create_users = f"""
        INSERT INTO
          `{tab}` (`family`, `name`, `patronymic`, `namber`, `post`, `address`, `password`)
        VALUES
          ('{family}', '', '', 0, '{post}', '', '{password}');
        """
    try:
        execute_query(connection, create_users)
    except: pass


def load(data, table): #на вход массив с данными
    for i in range(len(data)):
        for x in range(4):
            table.setItem(i,x,QtWidgets.QTableWidgetItem(data[i][x])) #i - строка x - столбец data[i][x] - сами данные

def frmedr(tab):
    select = f"SELECT * FROM {tab}"
    bigdata = execute_read_query(connection, select)
    data = []
    for i in bigdata:
        data.append([str(i[1]), str(i[2]), str(i[3]), str(i[4])])
    return data



###ПОИСК ПО КОДУ КЛИЕНТА
def findklient(userid, date):
    select_users = f"SELECT * FROM `appendix to the order`"
    users = execute_read_query(connection, select_users)
    for user in users:
        if user[2]==userid and user[1]==date:
            idord = user[0]
            idchel = user[3]
    select = f"SELECT `dish code`, `quantity` FROM `orders` WHERE `id`={idord}"
    us = execute_read_query(connection, select)
    for i in us:
        kolvo = i[1]
        dishcode = i[0]
    selmenu = f"SELECT `name`, `price` FROM `menu` WHERE `id`={dishcode}"
    selmenuF = execute_read_query(connection, selmenu)
    for j in selmenuF:
        nameeda = str(j[0])
        resprice = j[1]*kolvo
    selchel = f"SELECT `name` FROM `employee` WHERE `id`={idchel}"
    selchelF = execute_read_query(connection, selchel)
    for j in selchelF:
        namechel = j[0]
    return nameeda, kolvo, namechel, resprice




###ПОИСК ПОСТАВЩИКА
def findpostav(postavid, date):
    sel = f"SELECT `supplier code`, `employee` FROM `supply` WHERE `id`={postavid} and `delivery date`='{date}'"
    ps = execute_read_query(connection, sel)
    for j in ps:
        idpost = j[0]
        idsotr = j[1]

    selpr = f"SELECT `company name` FROM `suppliers` WHERE `id`={idpost}"
    rs = execute_read_query(connection, selpr)
    for g in rs:
        compname = g[0]

    selchel = f"SELECT `name` FROM `employee` WHERE `id`={idsotr}"
    ls = execute_read_query(connection, selchel)
    for k in ls:
        chelname = k[0]

    select = f"SELECT `quantity`, `price`, `weight`, `accepted positions` FROM `appendix to the delivery` WHERE `id`={idpost}"
    us = execute_read_query(connection, select)
    massiv = [compname, us[0][0], us[0][2], us[0][1], us[0][3], chelname]
    return massiv

def findremains(date, prod):
    selectprod = f"SELECT `product`, `sold`, `accepted`, `data`, `remains` FROM sold WHERE `product`='{prod}' and `data`='{date}'"
    selp = execute_read_query(connection, selectprod)
    return selp

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(350, 400))
        MainWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labeldobro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeldobro.setFont(font)
        self.labeldobro.setObjectName("labeldobro")
        self.verticalLayout.addWidget(self.labeldobro)
        self.labelnamedobro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelnamedobro.setFont(font)
        self.labelnamedobro.setObjectName("labelnamedobro")
        self.verticalLayout.addWidget(self.labelnamedobro)
        self.lineEditnamedobro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditnamedobro.setObjectName("lineEditnamedobro")
        self.verticalLayout.addWidget(self.lineEditnamedobro)
        self.labeldolzhdobro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeldolzhdobro.setFont(font)
        self.labeldolzhdobro.setObjectName("labeldolzhdobro")
        self.verticalLayout.addWidget(self.labeldolzhdobro)
        self.lineEditdolzhdobro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditdolzhdobro.setObjectName("lineEditdolzhdobro")
        self.verticalLayout.addWidget(self.lineEditdolzhdobro)
        self.labelpassdobro = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelpassdobro.setFont(font)
        self.labelpassdobro.setObjectName("labelpassdobro")
        self.verticalLayout.addWidget(self.labelpassdobro)
        self.lineEditpassdobro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditpassdobro.setObjectName("lineEditpassdobro")
        self.verticalLayout.addWidget(self.lineEditpassdobro)
        self.butjoindobro = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.butjoindobro.setFont(font)
        self.butjoindobro.setObjectName("butjoindobro")
        self.verticalLayout.addWidget(self.butjoindobro)
        self.butcreatedobro = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.butcreatedobro.setFont(font)
        self.butcreatedobro.setObjectName("butcreatedobro")
        self.verticalLayout.addWidget(self.butcreatedobro)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бургер Кинг"))
        self.labeldobro.setText(_translate("MainWindow", "Добро пожаловать в Бургер Кинг"))
        self.labelnamedobro.setText(_translate("MainWindow", "Фамилия"))
        self.labeldolzhdobro.setText(_translate("MainWindow", "Должность"))
        self.labelpassdobro.setText(_translate("MainWindow", "Пароль"))
        self.butjoindobro.setText(_translate("MainWindow", "Войти"))
        self.butcreatedobro.setText(_translate("MainWindow", "Создать"))


    def openCreateWindow(self):
        CreateWindow = QtWidgets.QWidget()
        create = Ui_MainWindow()
        create.setupUi(CreateWindow)
        CreateWindow.show()

class Ui_CreateWindow(object):
    def setupUi(self, CreateWindow):
        CreateWindow.setObjectName("CreateWindow")
        CreateWindow.resize(350, 400)
        CreateWindow.setMinimumSize(QtCore.QSize(350, 400))
        CreateWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(CreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelnewnote = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelnewnote.setFont(font)
        self.labelnewnote.setObjectName("labelnewnote")
        self.verticalLayout.addWidget(self.labelnewnote)
        self.labelname = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelname.setFont(font)
        self.labelname.setObjectName("labelname")
        self.verticalLayout.addWidget(self.labelname)
        self.lineEditname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditname.setObjectName("lineEditname")
        self.verticalLayout.addWidget(self.lineEditname)
        self.labeldolzh = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeldolzh.setFont(font)
        self.labeldolzh.setObjectName("labeldolzh")
        self.verticalLayout.addWidget(self.labeldolzh)
        self.lineEditdolzh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditdolzh.setObjectName("lineEditdolzh")
        self.verticalLayout.addWidget(self.lineEditdolzh)
        self.labelpass = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelpass.setFont(font)
        self.labelpass.setObjectName("labelpass")
        self.verticalLayout.addWidget(self.labelpass)
        self.lineEditpass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditpass.setObjectName("lineEditpass")
        self.verticalLayout.addWidget(self.lineEditpass)
        self.buttoncreatenew = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttoncreatenew.setFont(font)
        self.buttoncreatenew.setObjectName("buttoncreatenew")
        self.verticalLayout.addWidget(self.buttoncreatenew)
        CreateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        CreateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateWindow)
        self.statusbar.setObjectName("statusbar")
        CreateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CreateWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateWindow)

    def retranslateUi(self, CreateWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateWindow.setWindowTitle(_translate("CreateWindow", "Бургер Кинг"))
        self.labelnewnote.setText(_translate("CreateWindow", "Новая учетная запись"))
        self.labelname.setText(_translate("CreateWindow", "Фамилия"))
        self.labeldolzh.setText(_translate("CreateWindow", "Должность"))
        self.labelpass.setText(_translate("CreateWindow", "Пароль"))
        self.buttoncreatenew.setText(_translate("CreateWindow", "Создать"))

class Ui_ButtonsWindow(object):
    def setupUi(self, ButtonsWindow):
        ButtonsWindow.setObjectName("ButtonsWindow")
        ButtonsWindow.resize(350, 400)
        ButtonsWindow.setMinimumSize(QtCore.QSize(350, 400))
        ButtonsWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(ButtonsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.butzak = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.butzak.setFont(font)
        self.butzak.setObjectName("butzak")
        self.gridLayout.addWidget(self.butzak, 2, 0, 1, 1)
        self.butost = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.butost.setFont(font)
        self.butost.setObjectName("butost")
        self.gridLayout.addWidget(self.butost, 1, 0, 1, 1)
        self.butprod = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.butprod.setFont(font)
        self.butprod.setObjectName("butprod")
        self.gridLayout.addWidget(self.butprod, 3, 0, 1, 1)
        self.butpost = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.butpost.setFont(font)
        self.butpost.setObjectName("butpost")
        self.gridLayout.addWidget(self.butpost, 0, 0, 1, 1)
        ButtonsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ButtonsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        ButtonsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ButtonsWindow)
        self.statusbar.setObjectName("statusbar")
        ButtonsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ButtonsWindow)
        QtCore.QMetaObject.connectSlotsByName(ButtonsWindow)

    def retranslateUi(self, ButtonsWindow):
        _translate = QtCore.QCoreApplication.translate
        ButtonsWindow.setWindowTitle(_translate("ButtonsWindow", "Бургер Кинг"))
        self.butzak.setText(_translate("ButtonsWindow", "Заказы"))
        self.butost.setText(_translate("ButtonsWindow", "Остатки"))
        self.butprod.setText(_translate("ButtonsWindow", "Продукция"))
        self.butpost.setText(_translate("ButtonsWindow", "Поставка"))

class Ui_ProductsWindow(object):
    def setupUi(self, ProductsWindow):
        ProductsWindow.setObjectName("ProductsWindow")
        ProductsWindow.resize(890, 600)
        ProductsWindow.setMinimumSize(QtCore.QSize(890, 600))
        ProductsWindow.setMaximumSize(QtCore.QSize(890, 16777215))
        self.centralwidget = QtWidgets.QWidget(ProductsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabcold = QtWidgets.QWidget()
        self.tabcold.setObjectName("tabcold")
        self.gridLayout = QtWidgets.QGridLayout(self.tabcold)
        self.gridLayout.setObjectName("gridLayout")
        self.tableCold = QtWidgets.QTableWidget(self.tabcold)
        self.tableCold.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableCold.setAutoScroll(True)
        self.tableCold.setShowGrid(True)
        self.tableCold.setWordWrap(False)
        self.tableCold.setCornerButtonEnabled(False)
        self.tableCold.setRowCount(1000)
        self.tableCold.setColumnCount(4)
        self.tableCold.setObjectName("tableCold")
        item = QtWidgets.QTableWidgetItem()
        self.tableCold.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCold.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCold.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCold.setHorizontalHeaderItem(3, item)
        self.tableCold.horizontalHeader().setVisible(True)
        self.tableCold.horizontalHeader().setCascadingSectionResizes(False)
        self.tableCold.horizontalHeader().setDefaultSectionSize(170)
        self.tableCold.horizontalHeader().setHighlightSections(False)
        self.tableCold.horizontalHeader().setMinimumSectionSize(50)
        self.tableCold.horizontalHeader().setSortIndicatorShown(False)
        self.tableCold.horizontalHeader().setStretchLastSection(True)
        self.tableCold.verticalHeader().setVisible(False)
        self.tableCold.verticalHeader().setCascadingSectionResizes(False)
        self.tableCold.verticalHeader().setSortIndicatorShown(False)
        self.tableCold.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableCold, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabcold, "")
        self.tabdrinks = QtWidgets.QWidget()
        self.tabdrinks.setObjectName("tabdrinks")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabdrinks)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableDrinks = QtWidgets.QTableWidget(self.tabdrinks)
        self.tableDrinks.setRowCount(1000)
        self.tableDrinks.setObjectName("tableDrinks")
        self.tableDrinks.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrinks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrinks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrinks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDrinks.setHorizontalHeaderItem(3, item)
        self.tableDrinks.horizontalHeader().setDefaultSectionSize(170)
        self.tableDrinks.horizontalHeader().setMinimumSectionSize(50)
        self.tableDrinks.horizontalHeader().setStretchLastSection(True)
        self.tableDrinks.verticalHeader().setVisible(False)
        self.tableDrinks.verticalHeader().setHighlightSections(False)
        self.tableDrinks.verticalHeader().setSortIndicatorShown(False)
        self.tableDrinks.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableDrinks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabdrinks, "")
        self.tabmeat = QtWidgets.QWidget()
        self.tabmeat.setObjectName("tabmeat")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabmeat)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableMeat = QtWidgets.QTableWidget(self.tabmeat)
        self.tableMeat.setRowCount(1000)
        self.tableMeat.setObjectName("tableMeat")
        self.tableMeat.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeat.setHorizontalHeaderItem(3, item)
        self.tableMeat.horizontalHeader().setDefaultSectionSize(170)
        self.tableMeat.horizontalHeader().setHighlightSections(False)
        self.tableMeat.horizontalHeader().setMinimumSectionSize(50)
        self.tableMeat.horizontalHeader().setStretchLastSection(True)
        self.tableMeat.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableMeat, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabmeat, "")
        self.verticalLayout.addWidget(self.tabWidget)
        ProductsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProductsWindow)
        self.statusbar.setObjectName("statusbar")
        ProductsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProductsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProductsWindow)

    def retranslateUi(self, ProductsWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductsWindow.setWindowTitle(_translate("ProductsWindow", "Бургер Кинг"))
        self.tableCold.setSortingEnabled(False)
        item = self.tableCold.horizontalHeaderItem(0)
        item.setText(_translate("ProductsWindow", "Название"))
        item = self.tableCold.horizontalHeaderItem(1)
        item.setText(_translate("ProductsWindow", "Цена"))
        item = self.tableCold.horizontalHeaderItem(2)
        item.setText(_translate("ProductsWindow", "Срок годности"))
        item = self.tableCold.horizontalHeaderItem(3)
        item.setText(_translate("ProductsWindow", "Производитель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcold), _translate("ProductsWindow", "    Заморозка    "))
        item = self.tableDrinks.horizontalHeaderItem(0)
        item.setText(_translate("ProductsWindow", "Название"))
        item = self.tableDrinks.horizontalHeaderItem(1)
        item.setText(_translate("ProductsWindow", "Цена"))
        item = self.tableDrinks.horizontalHeaderItem(2)
        item.setText(_translate("ProductsWindow", "Срок годности"))
        item = self.tableDrinks.horizontalHeaderItem(3)
        item.setText(_translate("ProductsWindow", "Производитель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdrinks), _translate("ProductsWindow", "    Напитки    "))
        item = self.tableMeat.horizontalHeaderItem(0)
        item.setText(_translate("ProductsWindow", "Название"))
        item = self.tableMeat.horizontalHeaderItem(1)
        item.setText(_translate("ProductsWindow", "Цена"))
        item = self.tableMeat.horizontalHeaderItem(2)
        item.setText(_translate("ProductsWindow", "Срок годности"))
        item = self.tableMeat.horizontalHeaderItem(3)
        item.setText(_translate("ProductsWindow", "Производитель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmeat), _translate("ProductsWindow", "    Мясо    "))

class Ui_OrdersWindow(object):
    def setupUi(self, OrdersWindow):
        OrdersWindow.setObjectName("OrdersWindow")
        OrdersWindow.resize(890, 600)
        OrdersWindow.setMinimumSize(QtCore.QSize(890, 0))
        OrdersWindow.setMaximumSize(QtCore.QSize(890, 16777215))
        self.centralwidget = QtWidgets.QWidget(OrdersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMinimumSize(QtCore.QSize(130, 31))
        self.label.setMaximumSize(QtCore.QSize(130, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ClientCodeInputLine = QtWidgets.QLineEdit(self.splitter)
        self.ClientCodeInputLine.setMinimumSize(QtCore.QSize(111, 31))
        self.ClientCodeInputLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClientCodeInputLine.setFont(font)
        self.ClientCodeInputLine.setText("")
        self.ClientCodeInputLine.setObjectName("ClientCodeInputLine")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.DateOrderInputLine = QtWidgets.QLineEdit(self.groupBox)
        self.DateOrderInputLine.setMinimumSize(QtCore.QSize(111, 31))
        self.DateOrderInputLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DateOrderInputLine.setFont(font)
        self.DateOrderInputLine.setText("")
        self.DateOrderInputLine.setObjectName("DateOrderInputLine")
        self.gridLayout.addWidget(self.DateOrderInputLine, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(189, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(10000, 10000))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.OrderTable = QtWidgets.QTableWidget(self.groupBox)
        self.OrderTable.setRowCount(1000)
        self.OrderTable.setObjectName("OrderTable")
        self.OrderTable.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.OrderTable.setHorizontalHeaderItem(3, item)
        self.OrderTable.horizontalHeader().setCascadingSectionResizes(False)
        self.OrderTable.horizontalHeader().setDefaultSectionSize(200)
        self.OrderTable.horizontalHeader().setMinimumSectionSize(100)
        self.OrderTable.horizontalHeader().setSortIndicatorShown(False)
        self.OrderTable.horizontalHeader().setStretchLastSection(True)
        self.OrderTable.verticalHeader().setVisible(False)
        self.OrderTable.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.OrderTable, 1, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBox)
        OrdersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OrdersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        OrdersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OrdersWindow)
        self.statusbar.setObjectName("statusbar")
        OrdersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OrdersWindow)
        QtCore.QMetaObject.connectSlotsByName(OrdersWindow)

    def retranslateUi(self, OrdersWindow):
        _translate = QtCore.QCoreApplication.translate
        OrdersWindow.setWindowTitle(_translate("OrdersWindow", "MainWindow"))
        self.label.setText(_translate("OrdersWindow", "Код клиента"))
        self.label_2.setText(_translate("OrdersWindow", "Дата заказа"))
        self.pushButton.setText(_translate("OrdersWindow", "Узнать"))
        item = self.OrderTable.horizontalHeaderItem(0)
        item.setText(_translate("OrdersWindow", "Блюдо"))
        item = self.OrderTable.horizontalHeaderItem(1)
        item.setText(_translate("OrdersWindow", "Количество"))
        item = self.OrderTable.horizontalHeaderItem(2)
        item.setText(_translate("OrdersWindow", "Сотрудник"))
        item = self.OrderTable.horizontalHeaderItem(3)
        item.setText(_translate("OrdersWindow", "Цена"))

class Ui_ImportWindow(object):
    def setupUi(self, ImportWindow):
        ImportWindow.setObjectName("ImportWindow")
        ImportWindow.resize(890, 600)
        ImportWindow.setMinimumSize(QtCore.QSize(890, 0))
        ImportWindow.setMaximumSize(QtCore.QSize(890, 16777215))
        self.centralwidget = QtWidgets.QWidget(ImportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMinimumSize(QtCore.QSize(130, 31))
        self.label.setMaximumSize(QtCore.QSize(130, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CodeImportLine = QtWidgets.QLineEdit(self.splitter)
        self.CodeImportLine.setMinimumSize(QtCore.QSize(111, 31))
        self.CodeImportLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CodeImportLine.setFont(font)
        self.CodeImportLine.setText("")
        self.CodeImportLine.setObjectName("CodeImportLine")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.ImportTable = QtWidgets.QTableWidget(self.groupBox)
        self.ImportTable.setRowCount(1000)
        self.ImportTable.setObjectName("ImportTable")
        self.ImportTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(5, item)
        self.ImportTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ImportTable.horizontalHeader().setDefaultSectionSize(120)
        self.ImportTable.horizontalHeader().setMinimumSectionSize(100)
        self.ImportTable.horizontalHeader().setSortIndicatorShown(False)
        self.ImportTable.horizontalHeader().setStretchLastSection(True)
        self.ImportTable.verticalHeader().setVisible(False)
        self.ImportTable.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.ImportTable, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.DateImportLine = QtWidgets.QLineEdit(self.groupBox)
        self.DateImportLine.setMinimumSize(QtCore.QSize(111, 31))
        self.DateImportLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DateImportLine.setFont(font)
        self.DateImportLine.setText("")
        self.DateImportLine.setObjectName("DateImportLine")
        self.gridLayout.addWidget(self.DateImportLine, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(189, 23))
        self.pushButton_2.setMaximumSize(QtCore.QSize(189, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(200, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(189, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(189, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.groupBox)
        ImportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        ImportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImportWindow)
        self.statusbar.setObjectName("statusbar")
        ImportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ImportWindow)
        QtCore.QMetaObject.connectSlotsByName(ImportWindow)

    def retranslateUi(self, ImportWindow):
        _translate = QtCore.QCoreApplication.translate
        ImportWindow.setWindowTitle(_translate("ImportWindow", "MainWindow"))
        self.label.setText(_translate("ImportWindow", "Код поставки"))
        item = self.ImportTable.horizontalHeaderItem(0)
        item.setText(_translate("ImportWindow", "Поставщик"))
        item = self.ImportTable.horizontalHeaderItem(1)
        item.setText(_translate("ImportWindow", "Кол-во"))
        item = self.ImportTable.horizontalHeaderItem(2)
        item.setText(_translate("ImportWindow", "Вес"))
        item = self.ImportTable.horizontalHeaderItem(3)
        item.setText(_translate("ImportWindow", "Цена"))
        item = self.ImportTable.horizontalHeaderItem(4)
        item.setText(_translate("ImportWindow", "Принято"))
        item = self.ImportTable.horizontalHeaderItem(5)
        item.setText(_translate("ImportWindow", "Сотрудник"))
        self.label_2.setText(_translate("ImportWindow", "Дата поставки"))
        self.pushButton_2.setText(_translate("ImportWindow", "Узнать"))
        self.pushButton.setText(_translate("ImportWindow", "Организовать поставку"))

class Ui_RemainsWindow(object):
    def setupUi(self, RemainsWindow):
        RemainsWindow.setObjectName("RemainsWindow")
        RemainsWindow.resize(890, 600)
        RemainsWindow.setMinimumSize(QtCore.QSize(890, 0))
        RemainsWindow.setMaximumSize(QtCore.QSize(890, 16777215))
        self.centralwidget = QtWidgets.QWidget(RemainsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.DataLine = QtWidgets.QLineEdit(self.groupBox)
        self.DataLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DataLine.setFont(font)
        self.DataLine.setObjectName("DataLine")
        self.gridLayout.addWidget(self.DataLine, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.ImportTable = QtWidgets.QTableWidget(self.groupBox)
        self.ImportTable.setRowCount(1000)
        self.ImportTable.setObjectName("ImportTable")
        self.ImportTable.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ImportTable.setHorizontalHeaderItem(4, item)
        self.ImportTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ImportTable.horizontalHeader().setDefaultSectionSize(120)
        self.ImportTable.horizontalHeader().setMinimumSectionSize(100)
        self.ImportTable.horizontalHeader().setSortIndicatorShown(False)
        self.ImportTable.horizontalHeader().setStretchLastSection(True)
        self.ImportTable.verticalHeader().setVisible(False)
        self.ImportTable.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.ImportTable, 1, 0, 1, 5)
        self.ChooseProductLine = QtWidgets.QLineEdit(self.groupBox)
        self.ChooseProductLine.setMinimumSize(QtCore.QSize(111, 31))
        self.ChooseProductLine.setMaximumSize(QtCore.QSize(111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ChooseProductLine.setFont(font)
        self.ChooseProductLine.setText("")
        self.ChooseProductLine.setObjectName("ChooseProductLine")
        self.gridLayout.addWidget(self.ChooseProductLine, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(189, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(189, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        RemainsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RemainsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        RemainsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RemainsWindow)
        self.statusbar.setObjectName("statusbar")
        RemainsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RemainsWindow)
        QtCore.QMetaObject.connectSlotsByName(RemainsWindow)

    def retranslateUi(self, RemainsWindow):
        _translate = QtCore.QCoreApplication.translate
        RemainsWindow.setWindowTitle(_translate("RemainsWindow", "MainWindow"))
        self.label_2.setText(_translate("RemainsWindow", "Выберите продукт"))
        item = self.ImportTable.horizontalHeaderItem(0)
        item.setText(_translate("RemainsWindow", "Продукт"))
        item = self.ImportTable.horizontalHeaderItem(1)
        item.setText(_translate("RemainsWindow", "Продано"))
        item = self.ImportTable.horizontalHeaderItem(2)
        item.setText(_translate("RemainsWindow", "Принято"))
        item = self.ImportTable.horizontalHeaderItem(3)
        item.setText(_translate("RemainsWindow", "Дата"))
        item = self.ImportTable.horizontalHeaderItem(4)
        item.setText(_translate("RemainsWindow", "Остаток"))
        self.label.setText(_translate("RemainsWindow", "Выберите дату"))
        self.pushButton.setText(_translate("RemainsWindow", "Узнать"))

class Ui_AnketWindow(object):
    def setupUi(self, AnketWindow):
        AnketWindow.setObjectName("AnketWindow")
        AnketWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AnketWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_5 = QtWidgets.QSplitter(self.widget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_5 = QtWidgets.QLabel(self.splitter_5)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditDateOrder = QtWidgets.QLineEdit(self.splitter_5)
        self.lineEditDateOrder.setMinimumSize(QtCore.QSize(200, 31))
        self.lineEditDateOrder.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditDateOrder.setFont(font)
        self.lineEditDateOrder.setText("")
        self.lineEditDateOrder.setObjectName("lineEditDateOrder")
        self.gridLayout_2.addWidget(self.splitter_5, 4, 0, 1, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 31))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditAdressPostavka = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEditAdressPostavka.setMinimumSize(QtCore.QSize(200, 31))
        self.lineEditAdressPostavka.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditAdressPostavka.setFont(font)
        self.lineEditAdressPostavka.setText("")
        self.lineEditAdressPostavka.setObjectName("lineEditAdressPostavka")
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 2)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditDataPostavka = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEditDataPostavka.setMinimumSize(QtCore.QSize(200, 31))
        self.lineEditDataPostavka.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditDataPostavka.setFont(font)
        self.lineEditDataPostavka.setText("")
        self.lineEditDataPostavka.setObjectName("lineEditDataPostavka")
        self.gridLayout_2.addWidget(self.splitter_3, 2, 0, 1, 2)
        self.splitter_4 = QtWidgets.QSplitter(self.widget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_4 = QtWidgets.QLabel(self.splitter_4)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditOtv = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEditOtv.setMinimumSize(QtCore.QSize(200, 31))
        self.lineEditOtv.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditOtv.setFont(font)
        self.lineEditOtv.setText("")
        self.lineEditOtv.setObjectName("lineEditOtv")
        self.gridLayout_2.addWidget(self.splitter_4, 3, 0, 1, 2)
        self.lineEditPostavka = QtWidgets.QLineEdit(self.widget)
        self.lineEditPostavka.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPostavka.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditPostavka.setFont(font)
        self.lineEditPostavka.setText("")
        self.lineEditPostavka.setObjectName("lineEditPostavka")
        self.gridLayout_2.addWidget(self.lineEditPostavka, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        AnketWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnketWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AnketWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnketWindow)
        self.statusbar.setObjectName("statusbar")
        AnketWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnketWindow)
        QtCore.QMetaObject.connectSlotsByName(AnketWindow)

    def retranslateUi(self, AnketWindow):
        _translate = QtCore.QCoreApplication.translate
        AnketWindow.setWindowTitle(_translate("AnketWindow", "MainWindow"))
        self.label_5.setText(_translate("AnketWindow", "Дата заказа"))
        self.label_2.setText(_translate("AnketWindow", "Адрес поставки"))
        self.label_3.setText(_translate("AnketWindow", "Дата поставки"))
        self.label_4.setText(_translate("AnketWindow", "Ответственный"))
        self.label.setText(_translate("AnketWindow", "Выберите поставщика"))
        self.pushButton.setText(_translate("AnketWindow", "Сформировать поставку"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AnketWindow", "Продукт"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AnketWindow", "Кол-во"))

class Ui_DidWindow(object):
    def setupUi(self, DidWindow):
        DidWindow.setObjectName("DidWindow")
        DidWindow.resize(600, 537)
        DidWindow.setMinimumSize(QtCore.QSize(600, 0))
        DidWindow.setMaximumSize(QtCore.QSize(600, 16777215))
        self.centralwidget = QtWidgets.QWidget(DidWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_adres = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_adres.setFont(font)
        self.label_adres.setObjectName("label_adres")
        self.verticalLayout_2.addWidget(self.label_adres)
        self.label_date = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.verticalLayout_2.addWidget(self.label_date)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        DidWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DidWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        DidWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DidWindow)
        self.statusbar.setObjectName("statusbar")
        DidWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DidWindow)
        QtCore.QMetaObject.connectSlotsByName(DidWindow)

    def retranslateUi(self, DidWindow):
        _translate = QtCore.QCoreApplication.translate
        DidWindow.setWindowTitle(_translate("DidWindow", "MainWindow"))
        self.label.setText(_translate("DidWindow", "Поставка сформирована"))
        self.label_adres.setText(_translate("DidWindow", "ТЦ ЦУМ"))
        self.label_date.setText(_translate("DidWindow", "07.01.2023"))
        self.label_2.setText(_translate("DidWindow", "Адрес"))
        self.label_3.setText(_translate("DidWindow", "Дата"))
        self.label_4.setText(_translate("DidWindow", "Data"))
        self.label_5.setText(_translate("DidWindow", "Data"))
# инициализация
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
login = Ui_MainWindow()
login.setupUi(MainWindow)
MainWindow.show()
CreateWindow = QtWidgets.QMainWindow()
signin = Ui_CreateWindow()
signin.setupUi(CreateWindow)
ButtonsWindow = QtWidgets.QMainWindow()
button = Ui_ButtonsWindow()
button.setupUi(ButtonsWindow)
ProductsWindow = QtWidgets.QMainWindow()
product = Ui_ProductsWindow()
product.setupUi(ProductsWindow)
OrdersWindow=QtWidgets.QMainWindow()
orders=Ui_OrdersWindow()
orders.setupUi(OrdersWindow)
ImportWindow=QtWidgets.QMainWindow()
imports=Ui_ImportWindow()
imports.setupUi(ImportWindow)
RemainsWindow=QtWidgets.QMainWindow()
remains=Ui_RemainsWindow()
remains.setupUi(RemainsWindow)
AnketWindow=QtWidgets.QMainWindow()
anket=Ui_AnketWindow()
anket.setupUi(AnketWindow)
DidWindow=QtWidgets.QMainWindow()
did=Ui_DidWindow()
did.setupUi(DidWindow)
# обработка нажатий

def doing():
    login.butcreatedobro.clicked.connect(showCreateWindow)
    signin.buttoncreatenew.clicked.connect(registerNewUser)
    login.butjoindobro.clicked.connect(loginUser)
    button.butprod.clicked.connect(showProductsWindow)
    button.butzak.clicked.connect(showOrdersWindow)
    button.butost.clicked.connect(showRemainsWindow)
    button.butpost.clicked.connect(showImportWindow)
    orders.pushButton.clicked.connect(showOrders)
    remains.pushButton.clicked.connect(showRemains)
    imports.pushButton_2.clicked.connect(showImports)
    imports.pushButton.clicked.connect(showAnketWindow)
    anket.pushButton.clicked.connect(showDidWindow)

# функции

def showCreateWindow():
    CreateWindow.move(MainWindow.x(),MainWindow.y())
    CreateWindow.show()
    MainWindow.hide()

def showMainWindow():
    MainWindow.move(CreateWindow.x(),CreateWindow.y())
    MainWindow.show()
    CreateWindow.hide()

def showButtonsWindow():
    ButtonsWindow.show()
    MainWindow.hide()

def showProductsWindow():
    ###ВЫВОД ДАННЫХ В ТАБЛИЦЫ ЗАМОРОЗКИ, МЯСА И НАПИТКОВ
    load(frmedr('freezing'), product.tableCold)
    load(frmedr('meat'), product.tableMeat)
    load(frmedr('drinks'), product.tableDrinks)
    ProductsWindow.show()

def showOrdersWindow():
    OrdersWindow.show()

def showRemainsWindow():
    RemainsWindow.show()

def showImportWindow():
    ImportWindow.show()

def showAnketWindow():
    AnketWindow.show()

def showDidWindow():
    did.label_adres.setText(anket.lineEditAdressPostavka.text())
    did.label_date.setText(anket.lineEditDataPostavka.text())
    did.label_4.setText(anket.lineEditDateOrder.text())
    did.label_5.setText(anket.lineEditOtv.text())
    for i in range(anket.tableWidget.rowCount()):
        for x in range(2):
            did.tableWidget.setItem(i,x,QtWidgets.QTableWidgetItem(anket.tableWidget.item(i,x)))
    DidWindow.show()

def loginUser():
    name=login.lineEditnamedobro.text()
    dolzh=login.lineEditdolzhdobro.text()
    passw=login.lineEditpassdobro.text()
    loginUser_tobd(name,dolzh,passw)
def registerNewUser():
    name=signin.lineEditname.text()
    dolzh=signin.lineEditdolzh.text()
    passw=signin.lineEditpass.text()
    if name.strip()=="" or dolzh.strip()=="" or passw.strip()=="" or  not passw.isdigit() or not name.isalpha() or not dolzh.isalpha():
        message("Ошибка","Ошибка ввода значений","Фамилия: текст \nДолжность: текст \nПароль: число")
        return
    loadNewUser_tobd(name,dolzh,passw)
    showMainWindow()
def message(title,txt,infotxt=''):
    msg = QtWidgets.QMessageBox()
    msg.setIcon(QtWidgets.QMessageBox.Critical)
    msg.setText(txt)
    msg.setInformativeText(infotxt)
    msg.setWindowTitle(title)
    msg.exec_()
#СЮДА ЗАЛИВАТЬ ЮЗЕРА В БД
def loadNewUser_tobd(name,dolzh,passw, tab=' '):
    create(name, dolzh, int(passw), 'employee')
#СЮДА ПРОВЕРЯТЬ ЮЗЕРА В БД
def loginUser_tobd(name,dolzh,passw, tab=' '):
    find(name, dolzh, int(passw), 'employee')

def showOrders():
    for k in range(1000):
        for o in range(4):
            orders.OrderTable.setItem(k, o, QtWidgets.QTableWidgetItem(''))
    try:
        clientcode=orders.ClientCodeInputLine.text()
        date=orders.DateOrderInputLine.text()
        kortezh = findklient(int(clientcode), datetime.datetime.strptime(date, '%Y-%m-%d %H:%M:%S'))
        for i in range(4):
            orders.OrderTable.setItem(0,i,QtWidgets.QTableWidgetItem(str(kortezh[i])))
    except:
        message('Ошибка!', 'Ошибка!')


def showRemains():
    for k in range(1000):
        for o in range(5):
            remains.ImportTable.setItem(k, o, QtWidgets.QTableWidgetItem(''))
    date=remains.DataLine.text()
    product=remains.ChooseProductLine.text()
    print(date,product)
    try:
        kortezh = findremains(datetime.datetime.strptime(date, '%Y-%m-%d %H:%M:%S'), product)
        for i in range(5):
            for j in range(len(kortezh)):
                remains.ImportTable.setItem(j,i,QtWidgets.QTableWidgetItem(str(kortezh[j][i])))
    except:
        message('Ошибка!', 'Ошибка!')

def showImports():
    for k in range(1000):
        for o in range(6):
            imports.ImportTable.setItem(k, o, QtWidgets.QTableWidgetItem(''))
    code=imports.CodeImportLine.text()
    date=imports.DateImportLine.text()
    print(date,code)
    try:
        kortezh = findpostav(int(code), datetime.datetime.strptime(date, '%Y-%m-%d %H:%M:%S'))
        for i in range(6):
            imports.ImportTable.setItem(0,i,QtWidgets.QTableWidgetItem(str(kortezh[i])))
    except:
        message('Ошибка!', 'Ошибка!')

doing()
sys.exit(app.exec_())